### ISSUE TITLE
Controller sometimes fails even when it's connected to apiserver

### ISSUE THREAD

**Issue by floreks** [fest-research/iot-addon#1]
Controller exits with panic error after some time of running.

```
panic: IotDaemonSet ended early?

goroutine 1 [running]:
panic(0xeb1460, 0xc4204c7230)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fest-research/iot-addon/pkg/controller/watch.IotDaemonSetWatcher.Watch(0xc4203f27a0, 0xc4200a6e40)
	/home/floreks/Projects/go/src/github.com/fest-research/iot-addon/pkg/controller/watch/iotdaemonset.go:41 +0x5b4
main.main()
	/home/floreks/Projects/go/src/github.com/fest-research/iot-addon/cmd/controller/controller.go:32 +0x15f
```

Possibly this check is not needed at all. Check notifier implementation for apiserver.

**Comment by maciaszczykm** [comment]
Already done.
